# coding: utf-8
task :default => :build_js

desc "Build JavaScript"
task :build_js => ["public/js/page_index.js"]

file "public/js/page_index.js" => ["ovto/page_index.rb"] do |t|
  raise if 2 <= t.prerequisites.size # assert
  src_file = t.prerequisites[0]
  sh %Q! opal -I ovto --compile --gem ovto "#{src_file}" > "#{t.name}" !
end
